language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - npm install kelda/deployment-engine-downloader && ./node_modules/.bin/kelda-downloader

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint
    - ./kelda inspect ./slackinExample.js graphviz

notifications:
    slack:
        secure: GZDY6q2W6Biv4GOL/D4q3oIRo4TUGemM7w9oW/el9K2HNGVHZQtenSHfKFUD/rV8HntsatguaAd4gFsLp391PnpJzIhSlzDesz0q32wysW+y+ix8jG5T7FfVG7Ja0PTIYBOlPD06dp22JY13eiindO6ZE7xNo9SfduvFnEvLsiPe23mrivgxMGrqeCm7fGwQM8Ib2RAtdnQz8oWJCXrEnru1dRStxgA/dLHDLXYP/30OwGrZLH0W7HzEFbG5zRsScSPrhLtyiXhAWFKt87s8bbBOyxY/bJ91ak1y4ADT2ozP9gTNiTjeuGc5qW2TqTC+5tM2Ygy6LfSQQ/dqzFajImJRgDXmGkZq87k8OFbtBrzsRcjIPo0Ij7DLLJMhY3/L3qAwigrMnjSInj2vkPw4SrdsVBLOLxD2Vpu7i51ZIeISRVpaMGxFyjdA+cA4jvGz+CE1/ECz0RRqmiE1p/KfIjWa++GC0qB8BGY74TCTyhEUfLIIFhQ+jbNKOGzWs80Q8oJi+XQ7VLC2zTvu1IwfG6lmeg1XJfjrHteqY/ZcoNP1h7V3Tu8nUOAelCE/mHQjty3GhlX3d9NvmvYIyC4LwGUdYNcPRTrHetwZ8KtdNEQ1E6Dw2JF7B8nmbq34a0iYO+Dy3O40IvslRtpHD43qYU37sh8IP4LglMce/T0mFJE=
